[package]
name = "common_concept"
version = "0.1.0"
authors = ["lrtz <547617251lrtz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
